#!name=lesong 自用脚本 20220120
#!desc=20220120
#!system=ios15.1

[URL Rewrite]
# Rewrite Apple Weather Air Quality Map
^https?:\/\/weather-map\.apple\.com\/(v1|v2)\/mapOverlay\/airQuality\?x=(-?\d+)&y=(-?\d+)&z=(-?\d+).*(country=CN)?.* https://tiles.waqi.info/tiles/usepa-aqi/$4/$2/$3.png?&scale=2&country=US&colorFormat=agr header

[Script]
# > 京东App 历史价格 by Small
京东比价 = type=http-response,requires-body=1,pattern=^https?://api\.m\.jd\.com/client\.action\?functionId=(wareBusiness|serverConfig|basicConfig),script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/jd_tb_price.js

# > 淘宝App 历史价格 修改Surge语法 by Small
淘宝比价 = type=http-request,requires-body=1,pattern=^http://.+/amdc/mobileDispatch,script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/jd_tb_price.js
淘宝比价 = type=http-response,requires-body=1,pattern=^https?://trade-acs\.m\.taobao\.com/gw/mtop\.taobao\.detail\.getdetail,script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/jd_tb_price.js

# > 微信打开淘宝链接
微信打开淘宝链接 = type=http-response,pattern=^https?:\/\/weixin110\.qq\.com\/cgi-bin\/mmspamsupport-bin\/newredirectconfirmcgi,script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/WX-TB.js

# > 公众号去广告
公众号去广告 = requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/Wechat.js,type=http-response,pattern=^https?:\/\/mp\.weixin\.qq\.com\/mp\/getappmsgad,script-update-interval=0

# > 皮皮虾去广告
皮皮虾去广告 = requires-body=1,max-size=-1,script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/PPX.js,type=http-response,pattern=^https?://.*\.snssdk\.com/bds/(feed/stream|comment/cell_reply|cell/cell_comment|cell/detail|ward/list|user/favorite|user/cell_coment|user/cell_userfeed|user/publish_list),script-update-interval=0

# > bigshot会员
bigshot会员 = requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/Bigshot.js,type=http-response,pattern=^https:\/\/vni\.kwaiying\.com\/api\/v1\/user\/profile,script-update-interval=0

# > TF下载修正
TF下载修正 = type=http-request,pattern=^https?:\/\/testflight\.apple\.com\/v\d\/accounts\/.+?\/install$,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/TF.js

# > 百度防跳转
百度防跳转 = type=http-response,pattern=^https:\/\/boxer\.baidu\.com\/scheme\?scheme,script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/baidu-no-redirect.js

# > 哔哩哔哩, 港澳台番剧自动切换地区 & 显示豆瓣评分
Bili Region = type=http-response,pattern=^https:\/\/ap(p|i)\.bilibili\.com\/(pgc\/view\/(v\d\/)?app|x(\/v\d)?\/view\/video)\/(season|online)\?access_key,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/Bili_Auto_Regions.js
#可选, 适用于搜索指定地区的番剧
Bili Search = type=http-request,pattern=^https:\/\/app\.bilibili\.com\/x\/v\d\/search(\/type)?\?.+?%20(%E6%B8%AF|%E5%8F%B0|%E4%B8%AD)&,script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/Bili_Auto_Regions.js

# > JIBJAB vip
http-response https:\/\/origin-prod-phoenix\.jibjab\.com\/v1\/user requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/jibjab.js

# > PDF Expert vip
Documents-PdfExpert = type=http-response,pattern=^https:\/\/license\.pdfexpert\.com\/api\/.+\/subscription\/(refresh$|check$),requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/PDFexpert.js,script-update-interval=-1

# > 空气质量数据
空气质量 = script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/Apple_Weather.js,requires-body=1,tag=Apple_Weather,type=http-response,pattern=^https?:\/\/weather-data\.apple\.com\/(v1|v2)\/weather.*(?!dataSets=forecastNextHour)(include=.*air_quality.*|dataSets=.*airQuality.*).*(country=[A-Z]{2})?.*,max-size=0,script-update-interval=0


# > 酷我音乐vip
http-response ^https?:\/\/vip1\.kuwo\.cn\/(vip\/v2\/user\/vip|vip\/spi/mservice) requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Surge/JS/Kuwo.js
# > 酷我换肤(已经有的皮肤需要先从本地皮肤删除再换 By@ s y)
themekuwo.js = requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/nzw9314/QuantumultX/master/Script/themekuwo.js,type=http-response,pattern=^https?:\/\/vip1\.kuwo\.cn\/(vip\/v2\/theme)




[MITM]
hostname = %APPEND% api.m.jd.com, trade-acs.m.taobao.com, weather-data.apple.com, weather-map.apple.com, tiles.waqi.info, mp.weixin.qq.com, weixin110.qq.com, *.snssdk.com, vni.kwaiying.com, testflight.apple.com, boxer.baidu.com, ap?.bilibili.com, origin-prod-phoenix.jibjab.com, license.pdfexpert.com, *.kuwo.cn, vip1.kuwo.cn