#!name=lesong 自用脚本 20220120
#!desc=20220120
#!system=ios15.1

[URL Rewrite]
# Rewrite Apple Weather Air Quality Map
^https?:\/\/weather-map\.apple\.com\/(v1|v2)\/mapOverlay\/airQuality\?x=(-?\d+)&y=(-?\d+)&z=(-?\d+).*(country=CN)?.* https://tiles.waqi.info/tiles/usepa-aqi/$4/$2/$3.png?&scale=2&country=US&colorFormat=agr header

[Script]
# > 京东App 历史价格 by Small
京东比价 = type=http-response,requires-body=1,pattern=^https?://api\.m\.jd\.com/client\.action\?functionId=(wareBusiness|serverConfig|basicConfig),script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/jd_tb_price.js

# > 淘宝App 历史价格 修改Surge语法 by Small
淘宝比价 = type=http-request,requires-body=1,pattern=^http://.+/amdc/mobileDispatch,script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/jd_tb_price.js
淘宝比价 = type=http-response,requires-body=1,pattern=^https?://trade-acs\.m\.taobao\.com/gw/mtop\.taobao\.detail\.getdetail,script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/jd_tb_price.js

# > 微信打开淘宝链接
微信打开淘宝链接 = type=http-response,pattern=^https?:\/\/weixin110\.qq\.com\/cgi-bin\/mmspamsupport-bin\/newredirectconfirmcgi,script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/WX-TB.js

# > 公众号去广告
公众号去广告 = requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/Wechat.js,type=http-response,pattern=^https?:\/\/mp\.weixin\.qq\.com\/mp\/getappmsgad,script-update-interval=0

# > 皮皮虾去广告
皮皮虾去广告 = requires-body=1,max-size=-1,script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/PPX.js,type=http-response,pattern=^https?://.*\.snssdk\.com/bds/(feed/stream|comment/cell_reply|cell/cell_comment|cell/detail|ward/list|user/favorite|user/cell_coment|user/cell_userfeed|user/publish_list),script-update-interval=0

# > bigshot会员
bigshot会员 = requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/Bigshot.js,type=http-response,pattern=^https:\/\/vni\.kwaiying\.com\/api\/v1\/user\/profile,script-update-interval=0

# > 驾校e点通VIP
驾校e点通VIP= type=http-response,requires-body=1,pattern=^https:\/\/vipapi\.jxedt\.com\/vip\/check,max-size=0,script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/jxydt.js

# > TF下载修正
TF下载修正 = type=http-request,pattern=^https?:\/\/testflight\.apple\.com\/v\d\/accounts\/.+?\/install$,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/TF.js

# > 百度防跳转
百度防跳转 = type=http-response,pattern=^https:\/\/boxer\.baidu\.com\/scheme\?scheme,script-path=https://raw.githubusercontent.com/ventusoon/ventus/main/Script/baidu-no-redirect.js



[MITM]
hostname = %INSERT% api.m.jd.com, trade-acs.m.taobao.com, weather-data.apple.com, weather-map.apple.com, tiles.waqi.info, mp.weixin.qq.com, weixin110.qq.com, *.snssdk.com, vni.kwaiying.com, vipapi.jxedt.com, testflight.apple.com, boxer.baidu.com, *91*:8080, *my10api*:8080, vsco.co, api.revenuecat.com, ap?.bilibili.com, origin-prod-phoenix.jibjab.com, license.pdfexpert.com, *.kuwo.cn, vip1.kuwo.cn