#!name=Surge Cron Task
#!desc=Surge自动化脚本
#!system=ios
[Script]
Tasks: NASA每日一图 = type=cron,cronexp="5 0 * * *",script-path=https://raw.githubusercontent.com/evilbutcher/Quantumult_X/master/check_in/nasa/nasapic.js
Tasks: iDaily每日环球视野 = type=cron,cronexp="5 0 * * *",script-path=https://raw.githubusercontent.com/evilbutcher/Quantumult_X/master/check_in/idaily/idaily.js
Tasks: 天气预报 = type=cron,cronexp="00 6-21/3 * * *",script-path=https://raw.githubusercontent.com/lesong/QuantumultX/main/Surge/Weather.js
Tasks: 去哪儿 = type=cron,cronexp="4 0 * * *",script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/qunar/qunar.js
Tasks: 网易新闻 = type=cron,cronexp="4 0 * * *",script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/neteasenews/neteasenews.js
Tasks: 腾讯视频 = type=cron,cronexp="3 0 * * *",script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/videoqq/videoqq.js
Tasks: 10010 = type=cron,cronexp="0 9 * * *",script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/10010/10010.js,wake-system=true
Tasks: BiliBili = type=cron,cronexp="2 0 * * *",script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/bilibili/bilibili.js,wake-system=true
Tasks: WPS = type=cron,cronexp="0 9 * * *",script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/wps/wps.js,wake-system=true
Tasks: 叮咚买菜 = type=cron,cronexp="7 0 * * *",script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/mcdd/mcdd.js,wake-system=true
Tasks: 喜马拉雅 = type=cron,cronexp="4 0 * * *",script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/ximalaya/ximalaya.js,wake-system=true
Tasks: 百度贴吧 = type=cron,cronexp="1 0 * * *",script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/tieba/tieba.js,wake-system=true
Tasks: 美团 = type=cron,cronexp="7 0 * * *",script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/meituan/meituan.js,wake-system=true
Tasks: 苏宁易购 = type=cron,cronexp="7 0 * * *",script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/suning/suning.js,wake-system=true
Tasks: 顺丰速运 = type=cron,cronexp="6 0 * * *"script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/sfexpress/sfexpress.js,wake-system=true
Tasks: 网易云音乐 = type=cron,cronexp="1 7 * * *",script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/neteasemusic/neteasemusic.js,wake-system=true
Tasks: 字幕组 = type=cron,cronexp="3 0 * * *",script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/zimuzu/zimuzu.js,wake-system=true
什么值得买自动签到 = type=cron,cronexp="43 1/8 * * *",wake-system=1,timeout=3600,script-path=https://raw.githubusercontent.com/Tsukasa007/my_script/master/smzdm_mission.js




